# Generated by Django 3.1.7 on 2021-03-09 09:12

from django.db import migrations, models
import django.utils.timezone
import formation.models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_object', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[(formation.models.ContactStatus['RD'], 'READ'), (formation.models.ContactStatus['SP'], 'SPAM'), (formation.models.ContactStatus['UR'], 'UNREAD')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
