# Generated by Django 3.1.7 on 2021-03-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0008_auto_20210309_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
