version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      SECRET_KEY: 'a^cydtb3*9g3e+%ow=-cy+6c458@wu@g5t2^390y%ef&8u-@pr'
      DJANGO_SUPERUSER_PASSWORD: root
      DJANGO_SUPERUSER_USERNAME: root
      DJANGO_SUPERUSER_EMAIL: root@localhost.dev
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db

