# Generated by Django 3.1.7 on 2021-03-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0005_auto_20210309_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
