# Generated by Django 3.1.7 on 2021-03-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0012_auto_20210310_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='experiences',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
